use_frameworks!

platform :ios, '13.0'

target 'ExpenTrackerNetwork_Example' do
  pod 'ExpenTrackerNetwork', :path => '../'

  target 'ExpenTrackerNetwork_Tests' do
    inherit! :search_paths

    
  end
end
